/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

namespace RosSharp.RosBridgeClient.MessageTypes.Swc
{
    public class GPS : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "swc_msgs/GPS";

        public double lat;
        public double lon;

        public GPS()
        {
            this.lat = 0.0;
            this.lon = 0.0;
        }

        public GPS(double lat, double lon)
        {
            this.lat = lat;
            this.lon = lon;
        }
    }
}
